config/routes.rb
Rq::Application.routes.draw do

  get '/applications/:id/bucket/:bucket', to: 'applications#show_bucket', as: 'show_bucket_application'
  resources :applications

  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :users, :only => [:show]
  post '/events', to: 'events#create'

  root :to => "home#index"

  mount Resque::Server, :at => "/resque"

  

  

end

app/models/application.rb
class Application < ActiveRecord::Base
  RAW_EVENTS = 'events:raw'
  validates_uniqueness_of :name

  belongs_to :user
  has_many :metrics
end

app/models/event_application.rb
class EventApplication < ActiveRecord::Base
  RAW_EVENTS = 'events:raw'
  validates_uniqueness_of :name
end

app/models/metric.rb
class Metric < ActiveRecord::Base
  belongs_to :application

  validates :application_id, uniqueness: {scope: :bucket} 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :applications
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def event_handler
    @event_handler ||= RedisEvents.instance
  end

end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :set_application, only: [:show, :edit, :update, :destroy]
  before_action :is_logged_in

  def is_logged_in
    redirect_to new_user_session_path if current_user.nil? 
  end

  # GET /applications
  # GET /applications.json
  def index
    @applications = current_user.applications
  end

  # GET /applications/1
  # GET /applications/1.json
  def show
    @application = Application.find(params[:id])
  end

  # GET /applications/1
  # GET /applications/1.json
  def show_bucket
    @application = Application.find(params[:id])
    @bucket = params[:bucket]
    @metric = Metric.find_by(application_id: @application.id, bucket: @bucket)

    respond_to do |format|
      format.html { render 'show_bucket' }
      format.json { render action: 'show_bucket', location: @application }
    end
    
  end

  # GET /applications/new
  def new
    @application = Application.new
  end

  # GET /applications/1/edit
  def edit
  end

  # POST /applications
  # POST /applications.json
  def create
    @application = Application.new(application_params)
    @application.user = current_user


    respond_to do |format|
      if @application.save
        format.html { redirect_to @application, notice: 'Event application was successfully created.' }
        format.json { render action: 'show', status: :created, location: @application }
      else
        format.html { render action: 'new' }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applications/1
  # PATCH/PUT /applications/1.json
  def update
    respond_to do |format|
      if @application.update(application_params)
        format.html { redirect_to @application, notice: 'Event application was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application.destroy
    respond_to do |format|
      format.html { redirect_to applications_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application
      @application = Application.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def application_params
      params.require(:application).permit(:name, :user)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_filter :verify_authenticity_token, only: [:create]

  def create
    event_handler.dump_events(params[:raw_events])
    render status: 200, nothing: true
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  before_filter :update_sanitized_params, if: :devise_controller?

  def update
    @user = User.find(current_user.id)

    successfully_updated = if needs_password?(@user, params)
      @user.update_with_password(devise_parameter_sanitizer.sanitize(:account_update))
    else
      params[:user].delete(:current_password)
      @user.update_without_password(devise_parameter_sanitizer.sanitize(:account_update))
    end

    if successfully_updated
      set_flash_message :notice, :updated
      sign_in @user, :bypass => true
      redirect_to after_update_path_for(@user)
    else
      render "edit"
    end
  end


  private

  def needs_password?(user, params)
    user.email != params[:user][:email] || params[:user][:password].present?
  end

  def update_sanitized_params
    devise_parameter_sanitizer.for(:account_update).push(:phone_number, :skype, :timezone)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
 def devise_error_messages!
  return '' if resource.errors.empty?

  messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
  sentence = I18n.t('errors.messages.not_saved',
    count: resource.errors.count,
    resource: resource.class.model_name.human.downcase)

  html = %{
    <div class="alert alert-error alert-block"> <button type="button"
    class="close" data-dismiss="alert">x</button>
    <h4>#{sentence}</h4>
       #{messages}
    </div>
  }

  html.html_safe
 end
end

app/views/applications/_form.html.erb
<%= form_for(@application) do |f| %>
  <% if @application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@application.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
      <% @application.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/applications/edit.html.erb
<h1>Editing application</h1>

<%= render 'form' %>

<%= link_to 'Show', @application %> |
<%= link_to 'Back', applications_path %>

app/views/applications/index.html.erb
<h1>Listing applications</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @applications.each do |application| %>
      <tr>
        <td><%= application.name %></td>
        <td><%= link_to 'Show', application %></td>
        <td><%= link_to 'Edit', edit_application_path(application) %></td>
        <td><%= link_to 'Destroy', application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event application', new_application_path %>

app/views/applications/new.html.erb
<h1>New application</h1>

<%= render 'form' %>

<%= link_to 'Back', applications_path %>

app/views/applications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @application.name %>
  <br/>
  <strong>User:</strong>
  <%= @application.user.email %>
</p>

<div class="span12" >


  <div class="row" >
    <div class="span2">
      <ul class="nav nav-tabs nav-stacked">
        <% @application.metrics.each do |metric| %>
        <li><%= link_to metric.bucket, show_bucket_application_path(metric.application_id, metric.bucket) %></li>
        <% end %>
      </ul>
    </div>
    <div class="span10">

    </div>
  </div>

</div>


<%= link_to 'Edit', edit_application_path(@application) %> |
<%= link_to 'Back', applications_path %>

app/views/applications/show_bucket.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @application.name %>
  <br/>
  <strong>Bucket:</strong>
  <%= @bucket %>
</p>



<div class="span12" >


  <div class="row" >
    <div class="span12">

      <hr/>

      <div class="metrics">


        <div id="map-canvas" style="height:90%;top:30px"></div>


        
      </div>

      <hr/>


    </div>
  </div>

</div>
<%= link_to 'Edit', edit_application_path(@application) %> |
<%= link_to 'Back', applications_path %>





<hr/>


'<%= @metric.data %>'

<script type="text/javascript">
$(document).ready(function(){
  var metrics = new Metrics({
    container: ".metrics",
    data: $.parseJSON(<%= raw @metric.data.to_json %>)
  }).render();
});

</script>

app/views/event_applications/_form.html.erb
<%= form_for(@event_application) do |f| %>
  <% if @event_application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event_application.errors.count, "error") %> prohibited this event_application from being saved:</h2>

      <ul>
      <% @event_application.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>




<script type="text/javascript">
$(document).ready(function(){
  var timezone = jstz.determine();
  console.log(timezone.name()); 
});
</script>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="<%= root_path %>">Rq</a>
      <div class="container nav-collapse">
        <ul class="nav">
          <li><%= link_to "Applications", applications_path  %></li>
          <% if user_signed_in? %>
            <li><%= link_to "#{current_user.email}", user_path(current_user) %></li>
            <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
          <% else %>
            <li><%= link_to "Sign in", new_user_session_path %></li>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rq" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <%= render 'layouts/header' %>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
          
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h1>User#show</h1>
<%= @user.email %>

<br/>
<%= link_to 'Settings', edit_user_registration_path %>